version: "3"

services:
  consul-server-bootstrap:
    image: consul:1.4.0
    environment:
      -CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}
    volumes:
      - /var/consul_data:/tmp/consul
    network_mode: "host"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:53/udp"
    command: consul agent -node vm3  -advertise='{{GetInterfaceIP "ens33"}}' -client 0.0.0.0 -data-dir=/tmp/data -join 192.168.31.216
  #docker run  -p 9090:9090 -v /home/tianli/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus