version: "3"

services:
  consul-server-bootstrap:
    hostname: server
    image: consul:1.4.0
    environment:
      -CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}
    volumes:
      - /var/consul_data:/tmp/consul
    network_mode: "host"
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:53/udp"
    command: consul  agent -server -node master -advertise='{{GetInterfaceIP "ens33"}}' -join server  -bootstrap-expect 1 -ui -client 0.0.0.0 -data-dir=/tmp/data